<a href="https://colab.research.google.com/github/hannahTai/tibame-python/blob/main/python20260923.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import urllib.request as req

url = "https://raw.githubusercontent.com/Elwing-Chou/tibame20260826/refs/heads/main/total.csv"
req.urlretrieve(url, "total.csv")

('total.csv', <http.client.HTTPMessage at 0x7c34d142ec10>)

In [ ]:
import pandas as pd
df = pd.read_csv("total.csv", encoding="utf-8")
df

                    text    color  size  position   time     sn       userid
0                      簽  #A7FE39     1         0      0  30997     k9219059
1      2022.8.22第一個 耶～～😋  #FF02D3     2         0      2  30997  Amy20080403
2                      👌  #FFFFFF     1         0     10  30997      winolee
3             一集接一集停不下來～  #FFFFFF     1         0     35  30997  eggplant171
4           前面的，你每集都出現耶😂  #FFFFFF     1         0     37  30997  love3769846
...                  ...      ...   ...       ...    ...    ...          ...
36001              兩個大胸鬼  #FFFFFF     1         0  12939  30996       aaidjd
36002     龍顯蕙聲線真的很適合妖媚的鬼  #FFFFFF     1         0  13130  30996  eggplant171
36003               玟次郎？  #FDE53D     2         2  13855  30996      lpx1007
36004            戳爆他的泡泡！  #FFFFFF     1         0  13938  30996      LWT1109
36005    別把他弄醒了，睡著時比較可靠呀  #FFFFFF     1         0  13958  30996      gamefan

[36006 rows x 7 columns]

In [4]:
fil = [True, False, True]
df.head(3)[fil]

  text    color  size  position  time     sn    userid
0    簽  #A7FE39     1         0     0  30997  k9219059
2    👌  #FFFFFF     1         0    10  30997   winolee

In [8]:
# unique()/value_counts()
df["userid"].value_counts()
# userid
# asdf89aglkj	343
# trista771116	308

df["userid"].unique()
# array(['k9219059', 'Amy20080403', 'winolee', ..., 'huanqaq708', 'fire918',
#        'wasd123121'], dtype=object)

      text    color  size  position  time     sn    userid
0        簽  #A7FE39     1         0     0  30997  k9219059
348      簽  #A7FE39     1         0     0  30998  k9219059
12576    簽  #A7FE39     1         0     0  30992  k9219059
12846    簽  #A7FE39     1         0     0  31001  k9219059
25265    簽  #A7FE39     1         0     0  30991  k9219059
25679    簽  #A7FE39     1         0     0  30999  k9219059
25839    簽  #A7FE39     1         0     0  31000  k9219059
26141    簽  #A7FE39     1         0     0  30994  k9219059
32337    簽  #A7FE39     1         0    12  30995  k9219059
32542    簽  #A7FE39     1         0     0  30993  k9219059
35715    簽  #A7FE39     1         0     0  30996  k9219059

In [10]:
import os

# 建立資料夾
dn = "analyse"
if not os.path.exists(dn):
        os.makedirs(dn)

# 取出不重複的userid
uids = df["userid"].unique()

# loop userid
for uid in uids:
    # 產生過濾器
    fil = df["userid"] == uid # True,False...準備跟資料筆數一樣多的True/False
    # 過濾完的資料，存成csv
    df[fil].to_csv(f"{dn}/{uid}.csv", encoding="utf-8", index=False)

- pandas 兩大操作
    - 過濾: 移除不要的資料
        - 準備跟資料筆數一樣多的True/False, []帶入DataFrame

    - 轉換: 把整行轉換成另外一種格式

In [11]:
# 下載整個資料夾(Linux指令)
!zip -r /content/file.zip /content/analyse

串流輸出內容已截斷至最後 5000 行。
  adding: content/analyse/sf106053.csv (stored 0%)
  adding: content/analyse/kelly0906.csv (deflated 30%)
  adding: content/analyse/leejanet2310.csv (deflated 28%)
  adding: content/analyse/f401502.csv (deflated 50%)
  adding: content/analyse/peterya59.csv (deflated 39%)
  adding: content/analyse/peter30605.csv (deflated 43%)
  adding: content/analyse/boss10309.csv (deflated 12%)
  adding: content/analyse/xdxd075806.csv (deflated 1%)
  adding: content/analyse/auska0911.csv (deflated 41%)
  adding: content/analyse/st1255601.csv (deflated 64%)
  adding: content/analyse/zxc99720267.csv (deflated 11%)
  adding: content/analyse/fengyaochen.csv (stored 0%)
  adding: content/analyse/qwas12q.csv (stored 0%)
  adding: content/analyse/T25878787655.csv (deflated 21%)
  adding: content/analyse/l0limyl0ve.csv (deflated 1%)
  adding: content/analyse/ss961315906.csv (deflated 1%)
  adding: content/analyse/Beauty945.csv (deflated 34%)
  adding: content/analyse/q91148985.csv (deflated 3%)
  adding: content/analyse/sm0512.csv (deflated 23%)
  adding: content/analyse/leooelol.csv (deflated 1%)
  adding: content/analyse/WULIMG.csv (deflated 1%)
  adding: content/analyse/rex95146x.csv (deflated 18%)
  adding: content/analyse/asm09952.csv (deflated 3%)
  adding: content/analyse/lin1234h1.csv (deflated 23%)
  adding: content/analyse/john969123.csv (stored 0%)
  adding: content/analyse/gyrv0.csv (deflated 1%)
  adding: content/analyse/apink8660.csv (deflated 14%)
  adding: content/analyse/yueqi0810.csv (deflated 7%)
  adding: content/analyse/r0923521915.csv (deflated 4%)
  adding: content/analyse/cap543217636.csv (stored 0%)
  adding: content/analyse/wuszuwei.csv (deflated 22%)
  adding: content/analyse/Jeremylien.csv (deflated 9%)
  adding: content/analyse/Nicole0716.csv (deflated 4%)
  adding: content/analyse/s0870024.csv (stored 0%)
  adding: content/analyse/judy1659234.csv (deflated 7%)
  adding: content/analyse/BHSN00004sjq.csv (deflated 2%)
  adding: content/analyse/ajkli258.csv (deflated 31%)
  adding: content/analyse/Lucaslucaslu.csv (deflated 27%)
  adding: content/analyse/issac1120.csv (deflated 6%)
  adding: content/analyse/fechwej123.csv (stored 0%)
  adding: content/analyse/i200011212o.csv (deflated 18%)
  adding: content/analyse/kulokansi202.csv (deflated 42%)
  adding: content/analyse/cersei1201.csv (deflated 2%)
  adding: content/analyse/asl3457.csv (stored 0%)
  adding: content/analyse/top6116013.csv (deflated 2%)
  adding: content/analyse/ZhiqiQ1.csv (deflated 9%)
  adding: content/analyse/imdamaln.csv (deflated 9%)
  adding: content/analyse/Nikki54321.csv (deflated 21%)
  adding: content/analyse/scopio1966.csv (stored 0%)
  adding: content/analyse/Rita6146.csv (deflated 34%)
  adding: content/analyse/Allenking.csv (deflated 27%)
  adding: content/analyse/kun19960601.csv (deflated 1%)
  adding: content/analyse/williamis666.csv (deflated 21%)
  adding: content/analyse/tenghong.csv (deflated 30%)
  adding: content/analyse/Love891106.csv (deflated 8%)
  adding: content/analyse/andy841014.csv (deflated 2%)
  adding: content/analyse/ffthaktho.csv (deflated 39%)
  adding: content/analyse/sallychia.csv (deflated 1%)
  adding: content/analyse/BHSN000012nq.csv (deflated 28%)
  adding: content/analyse/adrian870107.csv (deflated 2%)
  adding: content/analyse/kazuketsu023.csv (stored 0%)
  adding: content/analyse/enialewong.csv (deflated 34%)
  adding: content/analyse/Sandy335577.csv (stored 0%)
  adding: content/analyse/aa30712791.csv (deflated 29%)
  adding: content/analyse/limaochen777.csv (deflated 17%)
  adding: content/analyse/wendylin1511.csv (deflated 9%)
  adding: content/analyse/BHSN00003jyz.csv (deflated 32%)
  adding: content/analyse/qwee50016.csv (deflated 16%)
  adding: content/analyse/st960903.csv (deflated 5%)
  adding: content/analyse/ray1080342.csv (deflated 27%)
  adding: content/analyse/Yusaki2008.csv (deflated 19%)
  adding: content/analyse/haha5213.csv (deflated 3%)
  adding: content/analyse/BHSN00000aip.csv (stored 0%)
  adding: content/analyse/as00142941.csv (stored 0%)
  adding: content/analyse/susan0521.csv (deflated 16%)
  adding: content/analyse/st3574303.csv (deflated 4%)
  adding: content/analyse/Lenny0924.csv (deflated 2%)
  adding: content/analyse/BHSN00003iut.csv (deflated 34%)
  adding: content/analyse/teaqqq.csv (deflated 26%)
  adding: content/analyse/Julie202052.csv (deflated 22%)
  adding: content/analyse/gn02034670.csv (deflated 13%)
  adding: content/analyse/J14900.csv (deflated 3%)
  adding: content/analyse/aa4207aa.csv (stored 0%)
  adding: content/analyse/candy072845.csv (deflated 47%)
  adding: content/analyse/sandy94279.csv (stored 0%)
  adding: content/analyse/ErikaMashiro.csv (deflated 18%)
  adding: content/analyse/Z0901212188.csv (deflated 20%)
  adding: content/analyse/zero20514.csv (deflated 1%)
  adding: content/analyse/Apple315412.csv (deflated 2%)
  adding: content/analyse/jack412.csv (deflated 20%)
  adding: content/analyse/tony829.csv (deflated 1%)
  adding: content/analyse/avi196464.csv (stored 0%)
  adding: content/analyse/Xinyin70793.csv (deflated 26%)
  adding: content/analyse/qzpo7532.csv (deflated 24%)
  adding: content/analyse/ShadowwodahS.csv (deflated 1%)
  adding: content/analyse/eggcat.csv (deflated 1%)
  adding: content/analyse/patty950909.csv (stored 0%)
  adding: content/analyse/L690723.csv (stored 0%)
  adding: content/analyse/a426.csv (deflated 2%)
  adding: content/analyse/edward961030.csv (stored 0%)
  adding: content/analyse/sheepiop890.csv (stored 0%)
  adding: content/analyse/tn00723719.csv (stored 0%)
  adding: content/analyse/c1080154.csv (deflated 45%)
  adding: content/analyse/Jerrye21.csv (deflated 4%)
  adding: content/analyse/k7t7v7.csv (deflated 8%)
  adding: content/analyse/aangel093.csv (deflated 1%)
  adding: content/analyse/parasunset.csv (deflated 41%)
  adding: content/analyse/xiaojerry10.csv (deflated 37%)
  adding: content/analyse/ysu784025.csv (deflated 29%)
  adding: content/analyse/victor890314.csv (stored 0%)
  adding: content/analyse/qkppil0678.csv (deflated 39%)
  adding: content/analyse/Kamisamaya.csv (stored 0%)
  adding: content/analyse/sele4827.csv (deflated 1%)
  adding: content/analyse/fire5526.csv (deflated 2%)
  adding: content/analyse/mouselin4260.csv (deflated 70%)
  adding: content/analyse/xuziqian411.csv (deflated 58%)
  adding: content/analyse/miss730506.csv (deflated 29%)
  adding: content/analyse/pinkcat2910.csv (deflated 1%)
  adding: content/analyse/wpoinp.csv (deflated 1%)
  adding: content/analyse/miss050you.csv (deflated 1%)
  adding: content/analyse/JFDJRR.csv (deflated 11%)
  adding: content/analyse/wsn0122.csv (deflated 41%)
  adding: content/analyse/Kaniku.csv (stored 0%)
  adding: content/analyse/tsubasa1995.csv (deflated 41%)
  adding: content/analyse/asdf1010215.csv (deflated 48%)
  adding: content/analyse/az819015.csv (stored 0%)
  adding: content/analyse/po789858961.csv (stored 0%)
  adding: content/analyse/Cindy0130.csv (deflated 2%)
  adding: content/analyse/yuchiao8787.csv (deflated 54%)
  adding: content/analyse/hsuyu1835.csv (deflated 33%)
  adding: content/analyse/E1114ren.csv (deflated 17%)
  adding: content/analyse/J32748067.csv (stored 0%)
  adding: content/analyse/fish6215tw.csv (stored 0%)
  adding: content/analyse/hvzrfmhsvx.csv (deflated 4%)
  adding: content/analyse/tipho.csv (deflated 18%)
  adding: content/analyse/Eremikalove.csv (deflated 41%)
  adding: content/analyse/zaqwaaaa.csv (deflated 22%)
  adding: content/analyse/ben710634.csv (deflated 46%)
  adding: content/analyse/yoshino0619.csv (deflated 19%)
  adding: content/analyse/emilylin58.csv (stored 0%)
  adding: content/analyse/Terry950721.csv (stored 0%)
  adding: content/analyse/ray20080827.csv (deflated 38%)
  adding: content/analyse/fyoutub22.csv (deflated 1%)
  adding: content/analyse/BHSN00001dqy.csv (stored 0%)
  adding: content/analyse/liao99101.csv (deflated 2%)
  adding: content/analyse/Xczy11530.csv (deflated 1%)
  adding: content/analyse/pcea1256.csv (stored 0%)
  adding: content/analyse/hueiyo0626.csv (stored 0%)
  adding: content/analyse/Ahaharico.csv (deflated 17%)
  adding: content/analyse/xs9988.csv (deflated 61%)
  adding: content/analyse/xmiao3.csv (deflated 4%)
  adding: content/analyse/DAS530520.csv (deflated 19%)
  adding: content/analyse/tuckman7777.csv (deflated 12%)
  adding: content/analyse/Koala682.csv (deflated 49%)
  adding: content/analyse/grace940620.csv (deflated 54%)
  adding: content/analyse/Hieuthao.csv (stored 0%)
  adding: content/analyse/Grace1009.csv (deflated 15%)
  adding: content/analyse/vvv19921012.csv (deflated 15%)
  adding: content/analyse/leo800819.csv (deflated 31%)
  adding: content/analyse/joey980616.csv (deflated 3%)
  adding: content/analyse/Selena960621.csv (deflated 15%)
  adding: content/analyse/huang910526.csv (deflated 27%)
  adding: content/analyse/ye20040715.csv (deflated 2%)
  adding: content/analyse/SHIUNN113.csv (deflated 37%)
  adding: content/analyse/Qooops.csv (deflated 26%)
  adding: content/analyse/maxint.csv (deflated 65%)
  adding: content/analyse/cgmbms2415.csv (deflated 8%)
  adding: content/analyse/gn00494808.csv (deflated 22%)
  adding: content/analyse/lol210577.csv (stored 0%)
  adding: content/analyse/animagnolia.csv (stored 0%)
  adding: content/analyse/f5ggffghnh.csv (deflated 28%)
  adding: content/analyse/d11122358.csv (deflated 15%)
  adding: content/analyse/jimmylin0512.csv (stored 0%)
  adding: content/analyse/aiko9269.csv (stored 0%)
  adding: content/analyse/ywwp8pggqj.csv (stored 0%)
  adding: content/analyse/red99279.csv (deflated 33%)
  adding: content/analyse/wrg2s2qqdx.csv (deflated 19%)
  adding: content/analyse/SAUCER.csv (deflated 3%)
  adding: content/analyse/XiaoYi87.csv (deflated 11%)
  adding: content/analyse/speng4227.csv (deflated 46%)
  adding: content/analyse/qjare.csv (deflated 19%)
  adding: content/analyse/cyu32d.csv (stored 0%)
  adding: content/analyse/pangya2007.csv (stored 0%)
  adding: content/analyse/bobo3056.csv (deflated 33%)
  adding: content/analyse/liiiieeiiiil.csv (deflated 24%)
  adding: content/analyse/keree123.csv (deflated 32%)
  adding: content/analyse/renee1024.csv (stored 0%)
  adding: content/analyse/theprocess16.csv (deflated 32%)
  adding: content/analyse/A22912507.csv (deflated 30%)
  adding: content/analyse/s622000w.csv (deflated 4%)
  adding: content/analyse/antichris66.csv (stored 0%)
  adding: content/analyse/AS70282.csv (deflated 1%)
  adding: content/analyse/ljn10607.csv (deflated 8%)
  adding: content/analyse/diidi033097.csv (deflated 23%)
  adding: content/analyse/dd1003960136.csv (stored 0%)
  adding: content/analyse/st104165.csv (stored 0%)
  adding: content/analyse/home50236.csv (deflated 20%)
  adding: content/analyse/gooddaytutu.csv (deflated 50%)
  adding: content/analyse/joy0808.csv (deflated 12%)
  adding: content/analyse/kow1527.csv (deflated 8%)
  adding: content/analyse/aa135335.csv (stored 0%)
  adding: content/analyse/klidofx.csv (deflated 1%)
  adding: content/analyse/kenwen1999.csv (deflated 7%)
  adding: content/analyse/flyinsky345.csv (deflated 5%)
  adding: content/analyse/peter610422.csv (stored 0%)
  adding: content/analyse/chang53m7.csv (deflated 20%)
  adding: content/analyse/W12431243945.csv (deflated 24%)
  adding: content/analyse/ncu103303505.csv (deflated 55%)
  adding: content/analyse/a000668515.csv (stored 0%)
  adding: content/analyse/pokjh684.csv (deflated 32%)
  adding: content/analyse/BHSN00003lil.csv (deflated 27%)
  adding: content/analyse/a34805.csv (deflated 57%)
  adding: content/analyse/k52013141798.csv (deflated 36%)
  adding: content/analyse/gg617can.csv (deflated 38%)
  adding: content/analyse/gb12345bg.csv (deflated 27%)
  adding: content/analyse/bgp895118.csv (deflated 4%)
  adding: content/analyse/Costa0502.csv (deflated 17%)
  adding: content/analyse/Z12435014.csv (stored 0%)
  adding: content/analyse/bonba.csv (deflated 38%)
  adding: content/analyse/s097006.csv (stored 0%)
  adding: content/analyse/reborn513231.csv (stored 0%)
  adding: content/analyse/junziyooo.csv (deflated 7%)
  adding: content/analyse/yu841027.csv (deflated 26%)
  adding: content/analyse/manpin1107.csv (stored 0%)
  adding: content/analyse/up6cjp6.csv (deflated 1%)
  adding: content/analyse/tea1122.csv (stored 0%)
  adding: content/analyse/h2735244.csv (deflated 3%)
  adding: content/analyse/Fkio.csv (stored 0%)
  adding: content/analyse/u154676.csv (deflated 46%)
  adding: content/analyse/yyun030.csv (deflated 9%)
  adding: content/analyse/a1090212.csv (stored 0%)
  adding: content/analyse/sally89327.csv (deflated 13%)
  adding: content/analyse/D2216182.csv (deflated 30%)
  adding: content/analyse/baby97389.csv (deflated 4%)
  adding: content/analyse/cell1234.csv (deflated 3%)
  adding: content/analyse/Cooper0604.csv (deflated 1%)
  adding: content/analyse/hiro6225.csv (deflated 15%)
  adding: content/analyse/MuMu0406.csv (stored 0%)
  adding: content/analyse/annmnnn9.csv (deflated 14%)
  adding: content/analyse/spring81400.csv (deflated 10%)
  adding: content/analyse/changeya.csv (deflated 42%)
  adding: content/analyse/whi69472.csv (stored 0%)
  adding: content/analyse/kiwieh0718.csv (deflated 10%)
  adding: content/analyse/sus383838.csv (deflated 3%)
  adding: content/analyse/bca96035.csv (deflated 2%)
  adding: content/analyse/BHSN00003op7.csv (stored 0%)
  adding: content/analyse/spirit153759.csv (deflated 1%)
  adding: content/analyse/zerg751014.csv (stored 0%)
  adding: content/analyse/linctus.csv (deflated 22%)
  adding: content/analyse/aaKiki1106.csv (deflated 2%)
  adding: content/analyse/ka7087.csv (deflated 10%)
  adding: content/analyse/rp4d9ftb7t.csv (deflated 17%)
  adding: content/analyse/Naughtychild.csv (deflated 33%)
  adding: content/analyse/raylan04100.csv (stored 0%)
  adding: content/analyse/a930722bo.csv (stored 0%)
  adding: content/analyse/stu895112.csv (deflated 4%)
  adding: content/analyse/hoshiran1201.csv (deflated 8%)
  adding: content/analyse/flc8197.csv (deflated 49%)
  adding: content/analyse/a80181.csv (deflated 1%)
  adding: content/analyse/ktchen2006.csv (deflated 14%)
  adding: content/analyse/a15588860.csv (stored 0%)
  adding: content/analyse/ez8zzero.csv (stored 0%)
  adding: content/analyse/brianyenyen.csv (deflated 4%)
  adding: content/analyse/alpaca48.csv (deflated 1%)
  adding: content/analyse/L13245678.csv (deflated 2%)
  adding: content/analyse/joe40817.csv (deflated 37%)
  adding: content/analyse/cc94e87879.csv (stored 0%)
  adding: content/analyse/gm571986.csv (stored 0%)
  adding: content/analyse/tw422.csv (stored 0%)
  adding: content/analyse/a2681556274.csv (stored 0%)
  adding: content/analyse/sky106057.csv (deflated 18%)
  adding: content/analyse/m880305.csv (deflated 33%)
  adding: content/analyse/k20089888.csv (deflated 2%)
  adding: content/analyse/Missidvovo.csv (deflated 6%)
  adding: content/analyse/bluesnow66.csv (deflated 59%)
  adding: content/analyse/d35168.csv (deflated 14%)
  adding: content/analyse/BHSN00003j5z.csv (deflated 46%)
  adding: content/analyse/W3410899.csv (stored 0%)
  adding: content/analyse/disu0609.csv (deflated 15%)
  adding: content/analyse/wps540623.csv (deflated 35%)
  adding: content/analyse/a36008x.csv (deflated 30%)
  adding: content/analyse/Sanygao2510.csv (deflated 1%)
  adding: content/analyse/Angel911025.csv (deflated 57%)
  adding: content/analyse/huang610483.csv (deflated 3%)
  adding: content/analyse/s0813707.csv (deflated 1%)
  adding: content/analyse/did90905.csv (stored 0%)
  adding: content/analyse/Jsiflvnx.csv (deflated 1%)
  adding: content/analyse/willyss9.csv (stored 0%)
  adding: content/analyse/cen526.csv (stored 0%)
  adding: content/analyse/Gina1228.csv (stored 0%)
  adding: content/analyse/diego525666.csv (deflated 39%)
  adding: content/analyse/May900531.csv (stored 0%)
  adding: content/analyse/jimmy930117.csv (stored 0%)
  adding: content/analyse/Joanna9898.csv (deflated 45%)
  adding: content/analyse/Ga2006150763.csv (deflated 25%)
  adding: content/analyse/A33194234.csv (deflated 3%)
  adding: content/analyse/patric70118.csv (deflated 1%)
  adding: content/analyse/lm896165.csv (deflated 2%)
  adding: content/analyse/dvcig0330.csv (deflated 1%)
  adding: content/analyse/YYY1456.csv (deflated 67%)
  adding: content/analyse/a6096533.csv (deflated 54%)
  adding: content/analyse/oxoukkk.csv (deflated 45%)
  adding: content/analyse/HaBenChen.csv (deflated 1%)
  adding: content/analyse/lovemejacky.csv (deflated 1%)
  adding: content/analyse/s790502ss.csv (deflated 9%)
  adding: content/analyse/eric960707.csv (deflated 19%)
  adding: content/analyse/ba1723m.csv (deflated 3%)
  adding: content/analyse/cow6956.csv (deflated 26%)
  adding: content/analyse/tso2065837.csv (deflated 20%)
  adding: content/analyse/Heroyuurei77.csv (deflated 5%)
  adding: content/analyse/gdd2501123.csv (deflated 20%)
  adding: content/analyse/QXYZQ.csv (stored 0%)
  adding: content/analyse/waiting09141.csv (deflated 2%)
  adding: content/analyse/burnett77.csv (deflated 29%)
  adding: content/analyse/dadkajf.csv (deflated 22%)
  adding: content/analyse/st0907958099.csv (stored 0%)
  adding: content/analyse/Bmvn.csv (deflated 22%)
  adding: content/analyse/abbbbbby.csv (deflated 30%)
  adding: content/analyse/Leafbeams.csv (deflated 36%)
  adding: content/analyse/BHSN00003u38.csv (deflated 26%)
  adding: content/analyse/spogebob360.csv (deflated 55%)
  adding: content/analyse/Laibrian2006.csv (stored 0%)
  adding: content/analyse/x5925033.csv (deflated 12%)
  adding: content/analyse/s10921319.csv (deflated 8%)
  adding: content/analyse/hhf05.csv (deflated 26%)
  adding: content/analyse/dnypkrhm2b.csv (deflated 20%)
  adding: content/analyse/liwenyan.csv (deflated 15%)
  adding: content/analyse/Andy87666.csv (deflated 2%)
  adding: content/analyse/nightcat9527.csv (stored 0%)
  adding: content/analyse/rr222tw.csv (deflated 24%)
  adding: content/analyse/wer927326.csv (deflated 45%)
  adding: content/analyse/QQ3216055890.csv (stored 0%)
  adding: content/analyse/e4898475.csv (deflated 19%)
  adding: content/analyse/BHSN00001h56.csv (deflated 19%)
  adding: content/analyse/satan723.csv (deflated 54%)
  adding: content/analyse/abc7619545.csv (deflated 41%)
  adding: content/analyse/belldiyas.csv (deflated 34%)
  adding: content/analyse/a991111.csv (deflated 30%)
  adding: content/analyse/juiyu621.csv (deflated 18%)
  adding: content/analyse/mandysmall.csv (deflated 16%)
  adding: content/analyse/ranjack06.csv (deflated 17%)
  adding: content/analyse/wujiadong.csv (deflated 18%)
  adding: content/analyse/yr107012.csv (deflated 1%)
  adding: content/analyse/York66690101.csv (stored 0%)
  adding: content/analyse/pudasun123.csv (deflated 5%)
  adding: content/analyse/sh92156123.csv (deflated 5%)
  adding: content/analyse/cpils456.csv (deflated 3%)
  adding: content/analyse/a5510jay.csv (stored 0%)
  adding: content/analyse/B9603.csv (deflated 43%)
  adding: content/analyse/z20587zl.csv (stored 0%)
  adding: content/analyse/BHSN00002r7g.csv (deflated 32%)
  adding: content/analyse/phelia721210.csv (deflated 55%)
  adding: content/analyse/zx14789kx.csv (stored 0%)
  adding: content/analyse/hello1999.csv (stored 0%)
  adding: content/analyse/Zhengcoco.csv (deflated 24%)
  adding: content/analyse/betty1000111.csv (deflated 28%)
  adding: content/analyse/youxuanshi.csv (deflated 42%)
  adding: content/analyse/slowpoke1125.csv (deflated 35%)
  adding: content/analyse/pochen1204.csv (deflated 1%)
  adding: content/analyse/gg0322gg.csv (deflated 13%)
  adding: content/analyse/icc50678gmb.csv (deflated 1%)
  adding: content/analyse/lig63739.csv (deflated 12%)
  adding: content/analyse/ptg8kbfkhv.csv (deflated 17%)
  adding: content/analyse/lovesilive.csv (deflated 24%)
  adding: content/analyse/Nightorchid.csv (deflated 5%)
  adding: content/analyse/PXU1018.csv (deflated 41%)
  adding: content/analyse/arielin1009.csv (stored 0%)
  adding: content/analyse/NBAJason.csv (deflated 40%)